# Generated by Django 5.2.7 on 2025-10-30 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="ccategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.product"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images"),
        ),
    ]
